# Generated by Django 3.1.3 on 2020-11-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='grade',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three'), ('four', 'Four'), ('five', 'Five'), ('six', 'Six'), ('seven', 'Seven'), ('eight', 'Eight'), ('nine', 'Nine'), ('ten math', 'Ten Math'), ('ten science', 'Ten Science'), ('ten humanities', 'Ten Humanities'), ('eleven math', 'Eleven Math'), ('eleven science', 'Eleven Science'), ('eleven humanities', 'Eleven Humanities'), ('twelve math', 'Twelve Math'), ('twelve science', 'Twelve Science'), ('twelve humanities', 'Twelve Humanities')], max_length=100),
        ),
    ]
