# Generated by Django 3.1.3 on 2020-11-08 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20201108_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='users',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(null=True, related_name='classrooms_as_student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_as_teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ExamMark',
        ),
    ]
