# Generated by Django 3.1.3 on 2020-11-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201108_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_file',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
