# Generated by Django 3.1.3 on 2020-11-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201117_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.classroom'),
        ),
    ]
