name: CD

on:
  release:
    types:
      published
		
jobs:
  publish:
    runs-on: ubuntu-latest
		
    steps:
      - uses: actions/checkout@v2

      - name: action on release
        run: echo "this pipeline will be run when a version release deploy happened. so you can publish your product anywhere you want."

