name: CI 

on:
	push:
		branches: [ main ]
		

jobs:
	build:
		runs-on: ubuntu-latest


		steps:
			- uses: actions/checkout@v2

			-name: run a one-line script
			 run: echo "you can run any script here on demand"

			-name: a new script
				run: echo "for example you can run your integeration tests here like:\n./manage.py test\nbut because we hav'nt code anything we can't run test now"
